spring.application.name=V-Booth
server.port=${SPRING_SERVER_PORT}
spring.devtools.restart.enabled=false

# mendefine driver database (postgres)
spring.datasource.driver-class-name=org.postgresql.Driver

# untuk mengarahkan url ke db yang digunakan
spring.datasource.url=${SPRING_DATA_SOURCE_URL}

# untuk define username
spring.datasource.username=${SPRING_DATA_SOURCE_USERNAME}

# untuk define password
spring.datasource.password=${SPRING_DATA_SOURCE_PASSWORD}

# define hibernate dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# menitranslate Capital letter to _
# spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy

# show query
spring.jpa.show-sql=true

# auto generate table
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}


